services:
  server_docker:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: php_apache_python
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_python

  mysql:
    image: mysql:latest
    container_name: mysql_python
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/database:/docker-entrypoint-initdb.d
      - persistent_python:/var/lib/mysql:rw
    depends_on:
      - server_docker
    networks:
      - network_python

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_python
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_python

networks:
  network_python:
    name: network_python

volumes:
  persistent_python:
