services:
  server_docker:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BASE_IMAGE_VERSION: ${BASE_IMAGE_VERSION}
        BASE_IMAGE_VARIANT: ${BASE_IMAGE_VARIANT}
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: server_docker_${PROJECT_NAME}
    user: "${NEW_UID}:${NEW_GID}"
    ports:
      - "${APP_PORT}:8081"
    volumes:
      - ../.:/var/www/html
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql_${PROJECT_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql:rw
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_${PROJECT_NAME}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    name: network_${PROJECT_NAME}

volumes:
  mysql_data:
    name: persistent_${PROJECT_NAME}
